<div class="bb-debugger-bar">
	<div class="bb-debugger-container">
		<h1 class="logo">
			<a href="https://github.com/ismail0234/phalcon-bb-debugger" target="_blank">BB Debugger</a>
		</h1>
		<nav>
			<ul>
				<li class="bb-float-left">
					<a href="javascript:;" data-bb="querys">
						<span class="bb-label bb-secondary">

							<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"><path d="M22 18.055v2.458c0 1.925-4.655 3.487-10 3.487-5.344 0-10-1.562-10-3.487v-2.458c2.418 1.738 7.005 2.256 10 2.256 3.006 0 7.588-.523 10-2.256zm-10-3.409c-3.006 0-7.588-.523-10-2.256v2.434c0 1.926 4.656 3.487 10 3.487 5.345 0 10-1.562 10-3.487v-2.434c-2.418 1.738-7.005 2.256-10 2.256zm0-14.646c-5.344 0-10 1.562-10 3.488s4.656 3.487 10 3.487c5.345 0 10-1.562 10-3.487 0-1.926-4.655-3.488-10-3.488zm0 8.975c-3.006 0-7.588-.523-10-2.256v2.44c0 1.926 4.656 3.487 10 3.487 5.345 0 10-1.562 10-3.487v-2.44c-2.418 1.738-7.005 2.256-10 2.256z"/></svg>

							Querys (<?php echo count($querys); ?>)
						</span>
					</a>
				</li>

				<li class="bb-float-left">
					<a href="javascript:;" data-bb="servers">
						<span class="bb-label bb-secondary">
							
							<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"><path d="M24 21v-6h-18v6h18zm-3-4c.553 0 1 .448 1 1s-.447 1-1 1c-.552 0-1-.448-1-1s.448-1 1-1zm-7.806 0h1.275l-.864 2h-1.274l.863-2zm-2.141 0h1.275l-.863 2h-1.275l.863-2zm-2.19 0h1.275l-.863 2h-1.275l.863-2zm-4.863.941c-2.253-.29-4-2.194-4-4.524 0-2.252 1.626-4.121 3.767-4.506.177-3.294 2.895-5.911 6.233-5.911s6.056 2.617 6.233 5.911c2.005.361 3.541 2.029 3.729 4.089h-1.991c-.279-2.105-2.674-2.333-3.65-2.401.117-1.958-.555-5.599-4.321-5.599-4.438 0-4.359 4.75-4.321 5.599-.945-.037-3.679.341-3.679 2.818 0 1.223.856 2.245 2 2.511v2.013z"/></svg>

							Servers (<?php echo count($servers); ?>)
						</span>
					</a>
				</li>	

				<li class="bb-float-left">
					<a href="javascript:;" data-bb="cookie">
						<span class="bb-label bb-secondary">
							
							
							<svg width="12" height="12" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill-rule="evenodd" clip-rule="evenodd"><path d="M12.078 0c6.587.042 11.922 5.403 11.922 12 0 6.623-5.377 12-12 12s-12-5.377-12-12c3.887 1.087 7.388-2.393 6-6 4.003.707 6.786-2.722 6.078-6zm1.422 17c.828 0 1.5.672 1.5 1.5s-.672 1.5-1.5 1.5-1.5-.672-1.5-1.5.672-1.5 1.5-1.5zm-6.837-3c1.104 0 2 .896 2 2s-.896 2-2 2-2-.896-2-2 .896-2 2-2zm11.337-3c1.104 0 2 .896 2 2s-.896 2-2 2-2-.896-2-2 .896-2 2-2zm-6-1c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zm-9-3c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zm13.5-2c.828 0 1.5.672 1.5 1.5s-.672 1.5-1.5 1.5-1.5-.672-1.5-1.5.672-1.5 1.5-1.5zm-15-2c.828 0 1.5.672 1.5 1.5s-.672 1.5-1.5 1.5-1.5-.672-1.5-1.5.672-1.5 1.5-1.5zm6-2c.828 0 1.5.672 1.5 1.5s-.672 1.5-1.5 1.5-1.5-.672-1.5-1.5.672-1.5 1.5-1.5zm-3.5-1c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1z"/></svg>

							Cookie (<?php echo count($cookies); ?>)
						</span>
					</a>
				</li>								

				<li class="bb-float-right">
					<span class="bb-label bb-success" title="Php Code Speed">

						<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"><path d="M13 12l-.688-4h-.609l-.703 4c-.596.347-1 .984-1 1.723 0 1.104.896 2 2 2s2-.896 2-2c0-.739-.404-1.376-1-1.723zm-1-8c-5.522 0-10 4.477-10 10s4.478 10 10 10 10-4.477 10-10-4.478-10-10-10zm0 18c-4.411 0-8-3.589-8-8s3.589-8 8-8 8 3.589 8 8-3.589 8-8 8zm-2-19.819v-2.181h4v2.181c-1.438-.243-2.592-.238-4 0zm9.179 2.226l1.407-1.407 1.414 1.414-1.321 1.321c-.462-.484-.964-.926-1.5-1.328z"/></svg>

						<?php echo $time; ?> sn
					</span>
				</li>
				<li class="bb-float-right">
					<span class="bb-label bb-primary" title="Ram Usage">

						<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"><path d="M24 8h-24v7h24v-7zm-22 5l.863-3h1.275l-.863 3h-1.275zm2.066 0l.863-3h1.275l-.863 3h-1.275zm2.067 0l.863-3h1.275l-.864 3h-1.274zm2.066 0l.863-3h1.274l-.863 3h-1.274zm3.341 0h-1.274l.863-3h1.275l-.864 3zm9.46-.5c-.552 0-1-.448-1-1s.448-1 1-1c.553 0 1 .448 1 1s-.447 1-1 1zm3 4.5h-24v7h24v-7zm-22 5l.863-3h1.275l-.863 3h-1.275zm2.066 0l.863-3h1.275l-.863 3h-1.275zm2.067 0l.863-3h1.275l-.864 3h-1.274zm2.066 0l.863-3h1.274l-.863 3h-1.274zm3.341 0h-1.274l.863-3h1.275l-.864 3zm9.46-.5c-.552 0-1-.448-1-1s.448-1 1-1c.553 0 1 .448 1 1s-.447 1-1 1zm1-15.5h-20l4-6h12l4 6z"/></svg>

						<?php echo $memory; ?>
					</span>
				</li>
			</ul>
		</nav>
	</div>

	<div class="bb-container bb-querylogs bb-d-none" id="querys">
		<div class="bb-table-scrollbar">
		
			<table class="bb-table bb-table-hover">
			  <thead>
				<tr>
				  <th class="bb-text-center" width="5%" scope="col">#</th>
				  <th scope="col" class="bb-text-left bb-col-auto">Query</th>
				  <th class="bb-text-center" width="10%" scope="col">Speed</th>
				</tr>
			  </thead>
			  <tbody>
			  	<?php if (count($querys)): ?>
				  	<?php $counter = 1;
				  		foreach ($querys as $key => $value): ?>
						<tr>
						  	<td class="bb-text-center" width="5%" scope="row"><?php echo ($counter++); ?></td>
						  	<td class="bb-col-auto">
						  		<div class="bb-single-line">
						  			<?php echo $value["sql"]["raw"]; ?>
						  		</div>
						  	</td>
						  	<td class="bb-text-center" width="10%"><?php echo round($value["speed"] , 4); ?> sn</td>
						</tr>		  		
				  	<?php endforeach ?>			  		
			  	<?php else: ?>
			  		<tr>
			  			<td colspan="3" class="bb-text-center">Not found querys.</td>
			  		</tr>
			  	<?php endif ?>

			  </tbody>
			</table>
			
		</div>
	</div>

	<div class="bb-container bb-servers bb-d-none" id="servers">
		<div class="bb-table-scrollbar">
		
			<table class="bb-table bb-table-hover">
			  <thead>
				<tr>
				  <th class="bb-text-center" width="5%" scope="col">#</th>
				  <th scope="col" class="bb-text-left" width="25%" >Name</th>
				  <th class="bb-col-auto bb-text-left" scope="col">Value</th>
				</tr>
			  </thead>
			  <tbody>
			  	<?php if (count($servers)): ?>
				  	<?php $counter = 1;
				  		foreach ($servers as $key => $value): ?>
						<tr>
						  	<td class="bb-text-center" cope="row"><?php echo ($counter++); ?></td>
						  	<td>
						  		<div class="bb-single-line"><?php echo $key; ?></div>
						  	</td>
						  	<td class="bb-col-auto">
						  		<div class="bb-single-line"><?php echo $value; ?></div>
						  	</td>
						</tr>		  		
				  	<?php endforeach ?>			  		
			  	<?php else: ?>
			  		<tr>
			  			<td colspan="3" class="bb-text-center">Not found servers.</td>
			  		</tr>
			  	<?php endif ?>

			  </tbody>
			</table>
			
		</div>
	</div>

	<div class="bb-container bb-cookie bb-d-none" id="cookie">
		<div class="bb-table-scrollbar">
		
			<table class="bb-table bb-table-hover">
			  <thead>
				<tr>
				  <th class="bb-text-center" width="5%" scope="col">#</th>
				  <th scope="col" class="bb-text-left" width="25%" >Name</th>
				  <th class="bb-col-auto bb-text-left" scope="col">Value</th>
				</tr>
			  </thead>
			  <tbody>
			  	<?php if (count($cookies)): ?>
				  	<?php $counter = 1;
				  		foreach ($cookies as $key => $value): ?>
						<tr>
						  	<td class="bb-text-center" cope="row"><?php echo ($counter++); ?></td>
						  	<td>
						  		<div class="bb-single-line"><?php echo $key; ?></div>
						  	</td>
						  	<td class="bb-col-auto">
						  		<div class="bb-single-line"><?php echo $value; ?></div>
						  	</td>
						</tr>		  		
				  	<?php endforeach ?>			  		
			  	<?php else: ?>
			  		<tr>
			  			<td colspan="3" class="bb-text-center">Not found cookies.</td>
			  		</tr>
			  	<?php endif ?>

			  </tbody>
			</table>
			
		</div>
	</div>

	<div class="bb-container bb-session bb-d-none" id="session">
		<div class="bb-table-scrollbar">
		
			<table class="bb-table bb-table-hover">
			  <thead>
				<tr>
				  <th class="bb-text-center" width="5%" scope="col">#</th>
				  <th scope="col" class="bb-text-left" width="25%" >Name</th>
				  <th class="bb-col-auto bb-text-left" scope="col">Value</th>
				</tr>
			  </thead>
			  <tbody>
			  	<?php if (count($sessions)): ?>
				  	<?php $counter = 1;
				  		foreach ($sessions as $key => $value): ?>
						<tr>
						  	<td class="bb-text-center" cope="row"><?php echo ($counter++); ?></td>
						  	<td>
						  		<div class="bb-single-line"><?php echo $key; ?></div>
						  	</td>
						  	<td class="bb-col-auto">
						  		<?php if (is_array($value)): ?>
					  				<pre><?php echo nl2br(print_r($value, true)); ?></pre>
					  			<?php else: ?>
					  				<?php echo $value; ?>
						  		<?php endif ?>
						  	</td>
						</tr>		  		
				  	<?php endforeach ?>			  		
			  	<?php else: ?>
			  		<tr>
			  			<td colspan="3" class="bb-text-center">Not found sessions.</td>
			  		</tr>
			  	<?php endif ?>

			  </tbody>
			</table>
			
		</div>
	</div>	

</div>

